import { Product } from "./../typings";

export const products: Product[] = [
  {
    id: "basic",
    active: true,
    description: "",
    images: [],
    metadata: {
      portability: "true",
      resolution: "480p",
      videoQuality: "good",
    },
    name: "Basic Plan",
    role: null,
    stripe_metadata_portability: "true",
    stripe_metadata_resolution: "480p",
    stripe_metadata_videoQuality: "good",
    tax_code: null,
    prices: [
      {
        id: "",
        product: "",
        active: true,
        currency: "",
        unit_amount: 20,
        description: "",
        type: "recurring",
        interval: "month",
        interval_count: 20,
        trial_period_days: 30,
      },
    ],
  },
  {
    id: "standard",
    active: true,
    description: "",
    images: [],
    metadata: {
      portability: "true",
      resolution: "1080p",
      videoQuality: "better",
    },
    name: "Standard Plan",
    role: null,
    stripe_metadata_portability: "true",
    stripe_metadata_resolution: "1080p",
    stripe_metadata_videoQuality: "better",
    tax_code: null,
    prices: [
      {
        id: "",
        product: "",
        active: true,
        currency: "",
        unit_amount: 30,
        description: "",
        type: "recurring",
        interval: "month",
        interval_count: 20,
        trial_period_days: 30,
      },
    ],
  },
  {
    id: "premium",
    active: true,
    description: "",
    images: [],
    metadata: {
      portability: "true",
      resolution: "4k",
      videoQuality: "best",
    },
    name: "Premium Plan",
    role: null,
    stripe_metadata_portability: "true",
    stripe_metadata_resolution: "4k",
    stripe_metadata_videoQuality: "best",
    tax_code: null,
    prices: [
      {
        id: "",
        product: "",
        active: true,
        currency: "",
        unit_amount: 40,
        description: "",
        type: "recurring",
        interval: "month",
        interval_count: 20,
        trial_period_days: 30,
      },
    ],
  },
];
