import { motion } from "framer-motion";
import Head from "next/head";
import React from "react";
import Header from "../components/Header";
import AboutFeed from "../components/AboutFeed";
import Footer from "../components/Footer";

type Props = {};

function AboutPage({}: Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Netflix Desgin | About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header
        links={[
          "Netflix",
          "Trending",
          "Top",
          "Action",
          "Comedies",
          "Scary",
          "people",
          "about",
        ]}
      />
      <AboutFeed />
      <Footer />
    </motion.div>
  );
}

export default AboutPage;
