import { motion } from "framer-motion";
import Head from "next/head";
import { Movie } from "../../typings";
import requests from "../../utils/requests";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import DetailsFeed from "../../components/details/DetailsFeed";

type Props = { netflixOriginals: Movie[] };

const Details: NextPage<Props> = ({ netflixOriginals }) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Netflix Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.designbust.com/download/1037/png/netflix_logo_png_transparet512.png"
        />
      </Head>
      <DetailsFeed netflixOriginals={netflixOriginals} />
    </motion.div>
  );
};

export default Details;

export const getStaticProps: GetStaticProps = async () => {
  const [netflixOriginals] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
  ]);

  return {
    props: { netflixOriginals: netflixOriginals.results },
  };
};

export const getStaticPaths: GetStaticPaths = () => {
  return {
    paths: [
      { params: { movieId: "1" } },
      { params: { movieId: "2" } },
      { params: { movieId: "3" } },
      { params: { movieId: "4" } },
      { params: { movieId: "5" } },
    ],
    fallback: true,
  };
};
